package hr.fer.zemris.java.hw03.prob1;

// TODO: Auto-generated Javadoc
/**
 * The Class Token represents a single token generated by lexer.
 */
public class Token {
	
	/** The type of TokenType enum. */
	private TokenType type;
	
	/** The value. */
	private Object value;
	
	/**
	 * Instantiates a new token with the given type and value.
	 *
	 * @param type the type
	 * @param value the value
	 */
	public Token(TokenType type, Object value) {
		this.type = type;
		this.value = value;
	}
	
	/**
	 * Gets the value.
	 *
	 * @return the value
	 */
	public Object getValue() {
		return value;
	}
	
	/**
	 * Gets the type.
	 *
	 * @return the type
	 */
	public TokenType getType() {
		return type;
	}
}
